apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-node-mongo
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: docker-node-mongo
        image: charlesjatto/nodejsapp:v1
        ports:
        - containerPort: 3000
        env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/mongo" # MongoDB connection string