apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2 # Number of desired replicas
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: charlesjatto/python-flask-app:v2
          ports:
            - containerPort: 8000
