apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  selector:
    app: python-app # Match this label to your Deployment's pod template
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000 # Port your Python app listens on inside the pods
  type: ClusterIP # Change to NodePort or ClusterIP if needed
